export const membersData = [
    {
        email: "sita.bhattarai@test.com",
        username: "sita.bhattarai",
        gender: "female",
        dateOfBirth: "1993-05-15",
        name: "Sita Bhattarai",
        created: "2024-08-15",
        lastActive: "2024-09-03",
        description: "Sita is an environmental enthusiast who spends her weekends trekking in the Himalayas. With a background in digital marketing, she helps local businesses in Kathmandu thrive online. She also enjoys exploring Nepalese cuisine and photography.",
        city: "Kathmandu",
        country: "Nepal",
        image: "https://images.unsplash.com/photo-1501466044931-62695aada8e9" // Professional woman
    },
    {
        email: "maya.shrestha@test.com",
        username: "maya.shrestha",
        gender: "female",
        dateOfBirth: "1994-10-11",
        name: "Maya Shrestha",
        created: "2024-08-12",
        lastActive: "2024-09-01",
        description: "Maya, a software engineer and fitness enthusiast, balances coding with running marathons. She enjoys spending quiet evenings with her cat, Chhiring, in Pokhara.",
        city: "Pokhara",
        country: "Nepal",
        image: "https://images.pexels.com/photos/415829/pexels-photo-415829.jpeg" // Casual and athletic vibe
    },
    {
        email: "binita.rai@test.com",
        username: "binita.rai",
        gender: "female",
        dateOfBirth: "1991-01-19",
        name: "Binita Rai",
        created: "2024-08-22",
        lastActive: "2024-08-29",
        description: "A graphic designer with a vibrant style, Binita finds inspiration in the culture of Patan. She volunteers at art centers and enjoys community projects around the Kathmandu Valley.",
        city: "Patan",
        country: "Nepal",
        image: "https://images.unsplash.com/photo-1535713875002-d1d0cf377fde" // Artistic and creative
    },
    {
        email: "raju.tamang@test.com",
        username: "raju.tamang",
        gender: "male",
        dateOfBirth: "1992-06-13",
        name: "Raju Tamang",
        created: "2024-08-18",
        lastActive: "2024-08-30",
        description: "Raju, a UX/UI designer, is passionate about user-centered design. He spends his free time cycling and exploring the food scene in Kathmandu.",
        city: "Kathmandu",
        country: "Nepal",
        image: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e" // Tech-focused urban look
    },
    {
        email: "nima.sherpa@test.com",
        username: "nima.sherpa",
        gender: "male",
        dateOfBirth: "1990-12-25",
        name: "Nima Sherpa",
        created: "2024-08-21",
        lastActive: "2024-09-02",
        description: "A wellness coach, Nima is dedicated to mindfulness and meditation. He enjoys leading yoga sessions and spending mornings by the lakes in Pokhara.",
        city: "Pokhara",
        country: "Nepal",
        image: "https://images.pexels.com/photos/220453/pexels-photo-220453.jpeg" // Calm, wellness vibe
    },
    {
        email: "bikash.gurung@test.com",
        username: "bikash.gurung",
        gender: "male",
        dateOfBirth: "1992-03-05",
        name: "Bikash Gurung",
        created: "2024-08-17",
        lastActive: "2024-09-03",
        description: "Bikash is a software developer and a camping enthusiast. He enjoys building tech solutions and spending weekends exploring the hills with his family.",
        city: "Chitwan",
        country: "Nepal",
        image: "https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e" // Outdoors, tech enthusiast
    },
    {
        email: "anjali.adhikari@test.com",
        username: "anjali.adhikari",
        gender: "female",
        dateOfBirth: "1995-04-28",
        name: "Anjali Adhikari",
        created: "2024-08-23",
        lastActive: "2024-09-01",
        description: "Anjali is a young entrepreneur with a tech startup in Kathmandu. She enjoys outdoor activities like kayaking and hosting game nights with friends.",
        city: "Kathmandu",
        country: "Nepal",
        image: "https://images.unsplash.com/photo-1544005313-94ddf0286df2" // Young, vibrant, social vibe
    },
    {
        email: "ram.khadka@test.com",
        username: "ram.khadka",
        gender: "male",
        dateOfBirth: "1993-07-12",
        name: "Ram Khadka",
        created: "2024-08-14",
        lastActive: "2024-08-30",
        description: "Ram is committed to community service, working with social organizations around Nepal. He loves soccer and weekend hiking trips.",
        city: "Bhaktapur",
        country: "Nepal",
        image: "https://images.pexels.com/photos/614810/pexels-photo-614810.jpeg" // Community-oriented, outdoors vibe
    },
    {
        email: "deepak.bhandari@test.com",
        username: "deepak.bhandari",
        gender: "male",
        dateOfBirth: "1991-11-30",
        name: "Deepak Bhandari",
        created: "2024-08-19",
        lastActive: "2024-09-01",
        description: "A mechanical engineer passionate about DIY projects, Deepak enjoys working on cars and organizing road trips around Nepal.",
        city: "Lalitpur",
        country: "Nepal",
        image: "https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e" // Mechanical engineer with DIY look
    },
    {
        email: "dipa.kharel@test.com",
        username: "dipa.kharel",
        gender: "female",
        dateOfBirth: "1994-02-14",
        name: "Dipa Kharel",
        created: "2024-08-20",
        lastActive: "2024-09-03",
        description: "Dipa is a high school teacher specializing in social sciences. She spends her weekends exploring Nepal’s countryside and photography.",
        city: "Kavre",
        country: "Nepal",
        image: "https://images.unsplash.com/photo-1517841905240-472988babdf9" // Teaching and countryside look
    }
];
