import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";

import { Toaster } from "@/components/ui/toaster"


import {SessionProvider} from "next-auth/react";
import {SidebarDemo} from "@/components/SideBarCheck";
import AuthProvider from "@/context/AuthProvider";
import Navbar from "@/components/Navbar";



const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
    // const session = await auth()
    // console.log('Session:', session); // Debugging statement
    // const userId = session?.user?.id || 'Guest'; // Fallback to 'Guest' or similar
    // console.log(userId)
    // const isLoggedIn = false; // Replace with your actual logic
    // const user = { imageUrl: '' };

    return (
    <html lang="en">

      <body className={inter.className}>
      <AuthProvider>

        <Navbar />

        {children}
        <Toaster />
    </AuthProvider>
      </body>
    </html>
  );
}
