import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";

import { Toaster } from "@/components/ui/sonner"


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
    const isLoggedIn = false; // Replace with your actual logic
    const user = { imageUrl: '' };

    return (
    <html lang="en">
      <body className={inter.className}>
      <nav>

      <Header />
      </nav>
        {children}
        <Toaster />
      </body>
    </html>
  );
}
