import type { Metadata } from "next";
import localFont from "next/font/local";
import { Inter } from  'next/font/google'
import "./globals.css";
import { cn } from '@/lib/utils'
import {className} from "postcss-selector-parser";

const inter = Inter({
    subsets: ['latin']
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(inter.className, "antialiased min-h-screen")}
      >
        {children}
      </body>
    </html>
  );
}
