import type { Metadata } from "next";
import { Inter } from  'next/font/google'
import "./globals.css";
import { cn } from '@/lib/utils'
import {QueryProvider} from "@/components/query-provier";
import { Toaster } from "@/components/ui/sonner";

const inter = Inter({
    subsets: ['latin']
})

export const metadata: Metadata = {
  title: "Let's go",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(inter.className, "antialiased min-h-screen")}
      >
      <QueryProvider>
        <Toaster />
          {children}
      </QueryProvider>
      </body>
    </html>
  );
}
